"""The tools the WDK server serves, callable by a host in its own process."""

from veupathdb_mcp.tools.catalog_tools import (
    browse_search_categories,
    get_parameter_options,
    get_search_overview,
    get_search_param_specs,
    list_record_types,
    list_searches,
    list_transforms,
    lookup_phyletic_codes,
    resolve_search_parameters,
    search_catalog_index,
    search_example_plans,
    search_for_searches,
    validate_search_parameters,
)
from veupathdb_mcp.tools.user_tools import (
    count_plan_steps,
    create_gene_set_step,
    enrich_gene_ids,
    get_ai_expression_summary,
    get_step_download_url,
    get_step_estimated_size,
    get_step_gene_ids,
    get_step_sample_records,
    lookup_gene_records,
    resolve_gene_ids_to_records,
    run_control_tests_on_search,
    run_control_tests_on_step,
)

__all__ = [
    "browse_search_categories",
    "count_plan_steps",
    "create_gene_set_step",
    "enrich_gene_ids",
    "get_ai_expression_summary",
    "get_parameter_options",
    "get_search_overview",
    "get_search_param_specs",
    "get_step_download_url",
    "get_step_estimated_size",
    "get_step_gene_ids",
    "get_step_sample_records",
    "list_record_types",
    "list_searches",
    "list_transforms",
    "lookup_gene_records",
    "lookup_phyletic_codes",
    "resolve_gene_ids_to_records",
    "resolve_search_parameters",
    "run_control_tests_on_search",
    "run_control_tests_on_step",
    "search_catalog_index",
    "search_example_plans",
    "search_for_searches",
    "validate_search_parameters",
]
